fix(flake): include `*.nix` files in `git archive`
by not specifying `*.nix export-ignore` in `.gitattributes`.  Hopefully
this fixes this error for good:

    error: getting status of '/nix/store/kd87l94qzrkjrh91mrymdcqzllikslwj-source/flake.nix': No such file or directory

Where previous attempts (like removing `.gitattributes export-ignore`)
failed.

Oddly, it seems that changing *any* `export-ignore` directive in
`.gitattributes` "fixes" the problem, but only temporarily.  However,
since the error above complains specifically about a `*.nix` file, and
because all files not exluded in `.gitignore` or marked with
`export-ignore` in `.gitattributes` appear in the flake store path
(above, `/nix/store/kd87l94qzrkjrh91mrymdcqzllikslwj-source/flake.nix`),
it seems like un-ignoring all `*.nix` files ought to correct the
issue.